# This inventory describes a virtual machine that will be deployed on a SEAPATH
# cluster or standalone machine.
# It gives two examples, the first on a critical (real-time) VM and the second
# on a standard VM.
#
# Be careful that SEAPATH only handles how to deploy and run the virtual machine.
# It does not handle any virtual machine inner configuration.
#
# Replace all the TODOs to fit your physical machines.
# More informations on SEAPATH Wiki:
# - General inventory : https://lf-energy.atlassian.net/wiki/x/lIblAQ
# - guest.xml.j2 templated xml file : https://lf-energy.atlassian.net/wiki/x/ao3lAQ

---
VMs:
  hosts:
    testvm:
      vm_template: "../templates/vm/guest.xml.j2" # TODO: Replace with your template
      vm_disk:

      # Connection test part. Remove if your vm has no ssh connection
      ansible_host: 10.132.170.8 # TODO : Put the IP of your VM
      wait_for_connection: false

      # Configuration part. These variables only work with the guest.xml.j2 template
      vm_features: [] # features for real time VM with secure boot disabled

      bridges:
        - name: "br0"
          mac_address: "52:54:00:e4:ff:02" # TODO
            # Replace by the mac address you want for your VM


  vars:
    ansible_user: ansible # Only for connection test
